### PR TITLE
feat: add localizedText to input text

### PR DESCRIPTION
**Pull request by leethree**

### CODE REVIEW

**Comment by mattyclarkson** [comment]
Is this here to provide a localised version of `suggestions`? In the scope of an **input** this is a bit weird: how would you enter both the `text` *and* the localised text to fill out the class? I feel that the localisation level should be higher in the stack than this? Would it make sense to extend the interface in `conversation` where the localisations are needed?

**Comment by leethree** [comment]
@mattyclarkson yes it's for suggestions. but also we need to show the localized text of the input added to the chat. since we added `localizedText` to `dom`, I guess it make sense to do the same for `input`.

**Comment by mattyclarkson** [comment]
The `localisedText` makes sense on the `DOM` as it's a document, documents come in different languages. My point was that having `localisedText` on an input from a user doesn't make semantic sense, how can they enter two languages at the same time? It makes sense when someone taps on a suggestion as we have the localised text, but they can't enter it when using the text input bar (which we hide). Adding this results in something that is specific to our application and confuses the purpose of the interface/class/project: it's supposed to **just** be for input from the user. If someone wanted to use this project in another situation, what do they fill `localisedText` out with? What do they use it for?

If this here so that in `convertSuggestion` you can pass the `localisedText` to `InputText` and then in `ChatBot#handleInput` you pull off the `localisedText` into the `INodeImmutable`, you could create a custom class?

```ts
interface IInputTextLocalisedOptions extends IInputTextOptions {
  localisedText?: string;
}
class InputTextLocalised extends InputText {
  localisedText?: string;
  constructor(options: IInputTextLocalisedOptions) {
    super(options);
    this.localisedText = options.localisedText;
  }
}

  protected convertSuggestion(data: INodeImmutable): IInputImmutable {
    return isINodeText(data) ? new InputTextLocalised(data) : new InputText('Unsupported Suggestion…');
  }
```

This is obviously the same thing that you have done but puts it next to the location that you need it. If you feel that this *is* the right place for the localised text, let's merge it and move on.

**Comment by leethree** [comment]
@mattyclarkson I think it makes sense. I don't feel strongly this should be added to `input`. will add it to the app repo instead.

**Pull request closed without merging**
